zuul:
  #Service will be mapped under the /api URI
  prefix: /api
  routes:
    hello-server:
      path: /server/**
      serviceId: HELLO-SERVER
#      url: http://localhost:8071
    hello-client:
      path: /client/**
      serviceId: HELLO-CLIENT
#      url: http://localhost:8072

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
    instance:
      hostname: localhost

server:
  port: 8079

spring:
  application:
    name: zuul-service

#Increase the hystrix timeout to 60s (for all)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
